-- Base schema for the public tables in Supabase project qumvjdwimpvnaijjwght.
--
-- Captured 2026-09-07 by introspecting information_schema / pg_indexes /
-- pg_policy from the SQL Editor (the CLI `db dump` needs Docker, which isn't
-- installed on this machine). Column types, nullability, defaults, the
-- primary keys and the pre-existing indexes below are exact. The RLS policy
-- bodies were NOT captured verbatim — they are written here as fully
-- permissive (`true`), which matches how the site uses the anon key (direct
-- insert + select from client HTML). Verify/tighten if that ever matters.
--
-- The two later indexes (idx_wait_times_predictor, and originally a duplicate
-- recorded_at index) live in migrations/20260907054704_add_wait_times_indexes.sql,
-- not here. Rebuild order: apply this file, then `supabase db push`.

-- ---------------------------------------------------------------------------
-- wait_times — one row per ride per collector run (every 15 min, six parks)
-- ---------------------------------------------------------------------------
create table public.wait_times (
  id           bigint      generated by default as identity primary key,
  park         text        not null,   -- 'dl' 'dca' 'mk' 'epcot' 'hs' 'ak'
  ride_name    text        not null,
  wait_time    integer,                -- null when the ride is closed
  is_open      boolean     not null,
  recorded_at  timestamptz not null default now(),
  day_of_week  smallint    not null,   -- 0=Sun .. 6=Sat (Pacific)
  hour_of_day  smallint    not null,   -- 0..23 (Pacific)
  month        smallint    not null,   -- 1..12 (Pacific)
  is_weekend   boolean     not null,
  season       text        not null    -- 'holiday' 'summer' 'spring_break' 'regular'
);

-- Pre-existing indexes (made by hand early on):
create index idx_waits_lookup
  on public.wait_times using btree (park, ride_name, day_of_week, hour_of_day, season);
create index idx_waits_recorded_at
  on public.wait_times using btree (recorded_at);

alter table public.wait_times enable row level security;

create policy "Allow anon insert" on public.wait_times
  for insert to anon, authenticated with check (true);
create policy "Allow anon select" on public.wait_times
  for select to anon, authenticated using (true);

-- ---------------------------------------------------------------------------
-- conversations — MainStreet concierge chat history
-- ---------------------------------------------------------------------------
create table public.conversations (
  id          text        not null primary key,
  title       text        not null,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now(),
  messages    jsonb       not null default '[]'::jsonb
);

alter table public.conversations enable row level security;

create policy "public read write" on public.conversations
  for all to anon, authenticated using (true) with check (true);
